/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_footprint_avlab_teclab_jni_Mp3Endocder */

#ifndef _Included_com_footprint_avlab_teclab_jni_Mp3Endocder
#define _Included_com_footprint_avlab_teclab_jni_Mp3Endocder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_footprint_avlab_teclab_jni_Mp3Endocder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_footprint_avlab_teclab_jni_Mp3Endocder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
